spring:
  application:
    name: url-shortener

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  data:
    redis:
      url: ${SPRING_REDIS_URL}
      timeout: 2000ms
      ssl:
        enabled: false

app:
  base-url: ${APP_BASE_URL:http://localhost:8080/}

server:
  port: ${PORT:8080}

  logging:
    level:
      root: INFO
      org.springframework.web: DEBUG
      org.hibernate.SQL: DEBUG
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"